---
- name: Create keypair
  ec2_key:
    name: my_keypair
    key_material: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA9AAU4M782JrF7yNATVydw96DkyWKrU32ZBWji1Rd0+wrZQhphDWmR+JxcZRNlV/fMFQ4sy7KZpXkmOcH18j7eW/GZZWl06hWP+iK/BUsDZFMEf6NDMPNyrsVjitjoNPr5rq3Kokbh+o9SCbsoFXPc8LMmO+OHOseARLQWNtevxHRzc/LcHUgjg3q0IPjggeufae6YDJc3xpigMD10It9fDE535BCOK/CD2EyoOVwnl7OBw2BPBfZ9hMMPJdeJUWSDH13QfpQTTbfpVYH4jAKYm9bIXlYKGmec0W1bq0JmbsD1izxhRNvSAxKvw+vs60Q+Y0KaNk1npULIT17hPtF root@f4c3edee8b35'
  register: keypair

- name: set variable
  debug: var=keypair

- name: set keypair
  set_fact: keypair={{ keypair.key.name }}

- name: Launch_instance
  ec2:
    assign_public_ip: true
    vpc_subnet_id: "{{ public_subnet1.subnet.id }}"
    keypair: "{{ keypair }}"
    group: "['{{ security_group1.group_name }}','{{ security_group2.group_name }}','{{ security_group3.group_name }}']"
    instance_type: "{{ instance_type }}"
    image: "{{ image_id }}"
    exact_count: 1
    count_tag: { "Name":"Jenkins" }
    instance_tags: { "Name":"Jenkins" }
    wait: true
  register: admin1

- name: set ec2_ip
  set_fact: ec2_ip={{ admin1.tagged_instances[0].public_ip }}

# when: admin1.instances[0].tags.Name =! Admin1-EC2

# - name: Add host
#   add_host:
#     name: "{{ item.public_ip }}"
#     groups: ec2_server
#   with_items: ec2.instances

- name: Add new IP to the hosts
  lineinfile:
    dest: "{{ playbook_dir }}/inventory/hosts"
    regexp: "^(.+)$"
    line: "{{ ec2_ip }} ansible_user=ec2-user become=true ansible_ssh_private_key_file={{ playbook_dir }}/keys/keypair.pem"

- name: Wait 300 seconds for port 22 to become open
  wait_for:
    port: 22
    host: '{{ ec2_ip }}'
    delay: 10
    timeout: 300

- name: Waiting for the ip in inventary host file
  pause:
    seconds: 10

